### ISSUE TITLE
Batch create mutation

### ISSUE THREAD

**Issue by star2000** [la4de/strawberry-graphql-django#3]
change
```graphql
mutation {
  createItem(data: {name: "item1"}) {
    id
  }
}
```
to
```graphql
mutation {
  createItems(data: [{name: "item1"}, {name: "item2"}]) {
    id
  }
}
```

**Comment by la4de** [comment]
It's good idea to have mutation for batch creation. Would you like to create a pull request?

I'd still keep the the old createItem mutation. We can deprecate it later.

**Comment by star2000** [comment]
> It's good idea to have mutation for batch creation. Would you like to create a pull request?
> 
> I'd still keep the the old createItem mutation. We can deprecate it later.

What formatting tools do you use, such as `autopep8`?

**Comment by la4de** [comment]
> > It's good idea to have mutation for batch creation. Would you like to create a pull request?
> > I'd still keep the the old createItem mutation. We can deprecate it later.
> 
> What formatting tools do you use, such as `autopep8`?

I'm using vim and it's formatting capabilities :). Anyway we really want to follow pep8.

**Comment by star2000** [comment]
When I format with autopep8, lines with more than 80 characters break.
Should I ignore this rule.

**Comment by la4de** [comment]
You ignore that now

**Comment by star2000** [comment]
https://github.com/la4de/strawberry-graphql-django/pull/5
